spring.application.name=currency-conversion
spring.config.import=optional:configserver:http://localhost:8888
server.port=8100

# Enable Feign clients (default: true in Spring Cloud)
spring.cloud.openfeign.enabled=true
# Default connection/read timeouts (ms)
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000
# Per-client config (replace 'currency-exchange' with your @FeignClient name)
spring.cloud.openfeign.client.config.currency-exchange.connect-timeout=2000
spring.cloud.openfeign.client.config.currency-exchange.read-timeout=2000
# Enable load balancer for Feign (default: true)
spring.cloud.openfeign.circuitbreaker.enabled=false
spring.cloud.loadbalancer.ribbon.enabled=false
# Set log level for a specific Feign client
logging.level.com.in28minutes.microservice.currencyconversionservice.CurrencyExchangeProxy=DEBUG

# Feign logger level: NONE, BASIC, HEADERS, FULL
spring.cloud.openfeign.client.config.default.logger-level=basic
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

#
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.h2.console.enabled=true
#spring.jpa.defer-datasource-initialization=true

management.tracing.sampling.probability=1.0
management.tracing.sampling.fraction=1.0
management.tracing.propagation.type=w3c
management.endpoints.web.exposure.include=*

#management.zipkin.tracing.endpoint=http://localhost:9411/v1/spans
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:9411/v1/traces

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.zipkin2=DEBUG
logging.level.io.opentelemetry=DEBUG
logging.level.io.micrometer=DEBUG
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000

#management.endpoints.web.exposure.include=*
