spring.application.name=restfull-web-services
logging.level.org.springframework=INFO

#spring.mvc.apiversion.use.path-segment=0

management.endpoints.web.exposure.include=*

# for H2 db
#spring.datasource.url = jdbc:h2:mem:testdb
#spring.h2.console.enabled=true

spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true

# ==== for MySQL Docker
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:mysql://localhost:3306/social_media_database
spring.datasource.username=social-media-user
spring.datasource.password=dummypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# aded by me to get JSON instead of XML
spring.mvc.contentnegotiation.default-content-type=application/json
spring.security.user.name=username
spring.security.user.password=password
